### PR TITLE
2 basic db implementation

### PR DESCRIPTION
**Pull request by ethanchou128**

### CODE REVIEW

**Comment by yenuGH** [comment]
i get the whole creating classes specific to mongodb (as it only works with primitives) but im guessing we'll have to create adapters for all of the classes once they're retreived

**Comment by ethanchou128** [comment]
@yenuGH yeah dw im planning on adding adapters/converters or whatever u want to call it after loading it in from the db

**Comment by ethanchou128** [comment]
@yenuGH ig just merge when ur done looking

**Comment by yenuGH** [comment]
only thing i think you should change is to make it so that the database initialization happens in the mainactivity

**Pull request merged**
